import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  metadataBase: new URL(process.env.NEXT_PUBLIC_BACKEND || 'http://localhost:3000'),
  title: "Workforce Monitoring",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
    apple: "/favicon.png",
  },
  openGraph: {
    title: "Workforce Monitoring",
    description: "Generated by create next app",
    images: "/favicon.png",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Workforce Monitoring",
    description: "Generated by create next app",
    images: ["/favicon.png"],
  }
};  

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
       {/* <Head>
        <link rel="icon" href="%PUBLIC_URL%/IMG/favicon.ico" />
      </Head> */}
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      
      </body>
    </html>
  );
}
